apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinematch
  labels:
    app: cinematch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cinematch
  template:
    metadata:
      labels:
        app: cinematch
    spec:
      containers:
      - name: cinematch
        image: flack74621/cinematch:latest  # Use your Docker Hub repository if pushed
        ports:
        - containerPort: 80
